/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import Manejadores.CreacionTablero;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author annelis
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelPartidasP = new javax.swing.JLabel();
        jTextFieldCampoID = new javax.swing.JTextField();
        jTextFieldCampoNombre = new javax.swing.JTextField();
        jTextFieldCampoApellido = new javax.swing.JTextField();
        jLabelAviso = new javax.swing.JLabel();
        jButtonSeleccion = new javax.swing.JButton();
        jScrollPaneMostrarDatos = new javax.swing.JScrollPane();
        jTextAreaArchivo = new javax.swing.JTextArea();
        jButtonJugar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Abyssinica SIL", 2, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("Registro de Jugador");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 250, 30));

        jButtonRegresar.setBackground(new java.awt.Color(255, 255, 0));
        jButtonRegresar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 110, 40));

        jLabelNombre.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 30));

        jLabelID.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(0, 0, 0));
        jLabelID.setText("ID:");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabelApellido.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApellido.setText("Apellido:");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 40));

        jLabelPartidasP.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jLabelPartidasP.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabelPartidasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jTextFieldCampoID.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCampoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, -1));

        jTextFieldCampoNombre.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 140, -1));

        jTextFieldCampoApellido.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCampoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 140, -1));

        jLabelAviso.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jLabelAviso.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAviso.setText("Seleccione el archivo a leer:");
        getContentPane().add(jLabelAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 40));

        jButtonSeleccion.setBackground(new java.awt.Color(0, 255, 204));
        jButtonSeleccion.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jButtonSeleccion.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSeleccion.setText("Selección");
        jButtonSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jScrollPaneMostrarDatos.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaArchivo.setColumns(20);
        jTextAreaArchivo.setRows(5);
        jScrollPaneMostrarDatos.setViewportView(jTextAreaArchivo);

        getContentPane().add(jScrollPaneMostrarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 260, 110));

        jButtonJugar.setBackground(new java.awt.Color(204, 0, 153));
        jButtonJugar.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jButtonJugar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonJugar.setText("Jugar");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 130, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugar.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 619));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // Instanciamos la ventana anterior para regresar a lo principal
        
        VentanaPrincipal vistaPrincipal = new VentanaPrincipal();
        vistaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionActionPerformed
       /**
     * Irá el método para que se pueda elegir el archivo, o sea que en este botón
     * se seleccionara el directorio donde esta guardado
     *abrira la carpeta principal de archivos...
     */
       
       JFileChooser abrirDirectorio = new  JFileChooser();
       abrirDirectorio.showOpenDialog(null);   //Esto nos sirve para no tener seleccionado ningun objeto
       File sinErrores = abrirDirectorio.getSelectedFile();
       
       
       //Hacemos un try-catch para evitar que nos de errores, por si se modifica o se borra 
       //por alguna razón el archivo a leer
       
       try{
           
           FileReader leer = new FileReader(sinErrores);
           BufferedReader memoriaArchivo = new BufferedReader(leer);
           String texto = "";
           String linea = "";
           
           //Este ciclo se usara para que cada linea que vaya recorriendo la vaya agregando
           //a la variable texto, más un salto de línea
           
           while (((linea = memoriaArchivo.readLine())!= null)){ 
               texto += linea +"\n";
           }
           
           //Se mostrará en el área de texto la información del archivo
           jTextAreaArchivo.setText(texto);
           JOptionPane.showMessageDialog(null, "Archivo leído correctamente");
       }  
       catch(Exception e){ 
       } 
    }//GEN-LAST:event_jButtonSeleccionActionPerformed

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // Una vez leído el archivo se llama al metodo apra crear el tablero
        
        CreacionTablero tablero = new CreacionTablero();
    }//GEN-LAST:event_jButtonJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSeleccion;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPartidasP;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPaneMostrarDatos;
    private javax.swing.JTextArea jTextAreaArchivo;
    private javax.swing.JTextField jTextFieldCampoApellido;
    private javax.swing.JTextField jTextFieldCampoID;
    private javax.swing.JTextField jTextFieldCampoNombre;
    // End of variables declaration//GEN-END:variables
}
