/*
 * Ira todo lo que es gráfico, como las ventanas y botones que tendran cada uno
*una cierta funcionalidad para poder jugar 
 */
package ventana;

/**
 *
 * @author annelis
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        //esto es para que aparezca en medio la ventana y no corrido hacia un lado
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jPanelFondoTablero = new javax.swing.JPanel();
        jButtonJugar = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jLabelDado = new javax.swing.JLabel();
        jLabelTituloPrincipal = new javax.swing.JLabel();
        jButtonFichaAmarilla = new javax.swing.JButton();
        jButtonFichaVerde = new javax.swing.JButton();
        jButtonDado = new javax.swing.JButton();
        jButtonFichaRojo = new javax.swing.JButton();
        jButtonFichaAzul = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 0));
        jButtonSalir.setFont(new java.awt.Font("Abyssinica SIL", 3, 18)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 31, 120, 40));

        jPanelFondoTablero.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanelFondoTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 610, 360));

        jButtonJugar.setBackground(new java.awt.Color(102, 255, 51));
        jButtonJugar.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jButtonJugar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonJugar.setText("Comenzar a jugar");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 200, 40));

        jButtonReportes.setBackground(new java.awt.Color(102, 255, 51));
        jButtonReportes.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jButtonReportes.setForeground(new java.awt.Color(0, 0, 0));
        jButtonReportes.setText("Reportes y Estadísticas");
        jButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 551, 240, 40));

        jLabelDado.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jLabelDado.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDado.setText("Tirar el dado");
        getContentPane().add(jLabelDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 140, 30));

        jLabelTituloPrincipal.setFont(new java.awt.Font("Abyssinica SIL", 2, 36)); // NOI18N
        jLabelTituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloPrincipal.setText("Serpientes y escaleras");
        getContentPane().add(jLabelTituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jButtonFichaAmarilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/amarillo.jpg"))); // NOI18N
        getContentPane().add(jButtonFichaAmarilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 70, 70));

        jButtonFichaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.jpg"))); // NOI18N
        getContentPane().add(jButtonFichaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 70, 70));

        jButtonDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado.jpg"))); // NOI18N
        jButtonDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, -1, -1));

        jButtonFichaRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rojo.jpg"))); // NOI18N
        getContentPane().add(jButtonFichaRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 70, 80));

        jButtonFichaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azul.jpg"))); // NOI18N
        getContentPane().add(jButtonFichaAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 70, 80));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // Llamaré al JFrame de Registro para que le salga al ususario la pestaña 
        //correspondiente 
        
        Registro vistaRegistro = new Registro();
        vistaRegistro.setVisible(true);
        
 /*
 * Dispose nos sirve para que cuando salga esta ventana secundaria la centana principal 
*desaparezca mientras estemos en esta, para mejor orden en vista y no se vea amontonado
 */
        this.dispose();
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // Llamaré al JFrame de Reporte para que al orprimir el botón salga la pestaña
        //correspondiente 
        
        Reporte vistaReporte = new Reporte();
        vistaReporte.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDado;
    private javax.swing.JButton jButtonFichaAmarilla;
    private javax.swing.JButton jButtonFichaAzul;
    private javax.swing.JButton jButtonFichaRojo;
    private javax.swing.JButton jButtonFichaVerde;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDado;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTituloPrincipal;
    private javax.swing.JPanel jPanelFondoTablero;
    // End of variables declaration//GEN-END:variables
}
